name: Unit Tests

on:
  - push
  - pull_request

jobs:
  check-unit-tests:
    name: Check Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Check Python unit tests
        run: |
          python3 -m pip install tox
          tox -e unit

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"

      - name: Run Go unit tests
        run: |
          set -eux
          (
            cd cluster-agent
            go test -v ./...
          )
